{
 "title": "Template - Cosmos",
 "description": "A dashboard for Cosmos-based blockchains. Based on DRSVLabs' work.",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load (1-5-15)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load Average 1" },
    { "expr": "node_load5", "legendFormat": "Load Average 5" },
    { "expr": "node_load15", "legendFormat": "Load Average 15" }
   ]
  },
  {
   "title": "Disk Space | Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sdb\"}/1073741824"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes/1073741824"
    }
   ]
  },
  {
   "title": "Disk Space | Root Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda1\"}/1073741824"
    }
   ]
  },
  { "title": "Sentinel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Signed blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_last_signed_height{instance=\"localhost:27660\"}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_height{instance=\"localhost:27660\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Liveness",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Liveness" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"localhost:27660\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "STAKED AMOUNT" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{instance=\"localhost:27660\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Interval (secs)",
   "type": "graph",
   "description": "Time between this and last block (Block.Header.Time) in seconds\n#\nDoesn't seem to receive any",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(tendermint_consensus_block_interval_seconds_count{instance=\"localhost:27660\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}